services:
  web:
    build:
      context: ./langchain-rag-fastapi
      dockerfile: Dockerfile
    container_name: rag_api
    ports:
      - "8000:8000"
    env_file:
      - ./langchain-rag-fastapi/.env 
    depends_on:
      - db
    command: uvicorn rag_project.api.server:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:15
    container_name: rag_postgres
    restart: always
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: npg_8olGPYMqE9yZ
      POSTGRES_DB: neondb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
